from __future__ import annotations

from django import forms
from django.contrib.auth.forms import AuthenticationForm, SetPasswordForm
from django.core.validators import RegexValidator


class DoctorRegistrationForm(forms.Form):
    doctor_id = forms.CharField(
        label="Doctor ID - autogenerated by the system",
        required=True,
        widget=forms.TextInput(attrs={"readonly": "readonly"}),
    )
    full_name = forms.CharField(label="Full Name", required=True)
    email = forms.EmailField(label="Doctor's email address", required=True)

    whatsapp_number = forms.CharField(
        label="Doctor's WhatsApp number - 10 digits",
        required=True,
        validators=[
            RegexValidator(r"^\d{10}$", "Enter a 10-digit WhatsApp number (without country code)."),
        ],
    )

    clinic_number = forms.CharField(
        label="Clinic's appointment booking phone number",
        required=True,
        validators=[
            RegexValidator(r"^\d{6,15}$", "Enter a valid phone number (digits only)."),
        ],
    )

    clinic_whatsapp_number = forms.CharField(
        label="Clinic's appointment booking WhatsApp number - 10 digits",
        required=True,
        validators=[
            RegexValidator(r"^\d{10}$", "Enter a 10-digit WhatsApp number (without country code)."),
        ],
    )

    imc_number = forms.CharField(
        label="Indian Medical Commission (IMC) ID",
        required=True,
        validators=[
            RegexValidator(r"^[0-9A-Za-z]+$", "Enter an alphanumeric IMC ID."),
        ],
        help_text="Alphanumeric",
    )

    postal_code = forms.CharField(
        label="Postal Code (6 digits)",
        required=True,
        validators=[
            RegexValidator(r"^\d{6}$", "Enter a valid 6-digit PIN code."),
        ],
    )

    address_text = forms.CharField(
        label="Clinic address",
        required=True,
        widget=forms.Textarea,
    )

    photo = forms.ImageField(label="Upload Photo", required=False)


class EmailAuthenticationForm(AuthenticationForm):
    username = forms.EmailField(label="Email")


class DoctorSetPasswordForm(SetPasswordForm):
    pass
